#!/bin/bash

certbot delete --agree-tos --non-interactive --cert-name BASE ; certbot certonly --agree-tos --non-interactive --renew-by-default --standalone --cert-name BASE --email hostmaster@$(hostname --domain) --rsa-key-size 4096 -d $(hostname)

find "/etc/letsencrypt"               -type d -exec chmod -f 0755 {} \; > /dev/null 2>&1
find "/etc/letsencrypt"   -executable -type f -exec chmod -f 0755 {} \; > /dev/null 2>&1
find "/etc/letsencrypt" ! -executable -type f -exec chmod -f 0644 {} \; > /dev/null 2>&1
