#!/bin/bash

while read -e ARG && test -n "${ARG}"; do
  key="$(echo "${ARG%%:*}" | xargs)"
  val="$(echo "${ARG#*:}" | xargs)"
  export ${key}="${val}"
done

external_phone_from_db="00421905123456"

echo "SET VARIABLE EXTNUM \"${external_phone_from_db}\""
